package com.xxmrk888ytxx.database.Entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * [Entity] for storing package names of applications added by the user.
 * This table ensures that each package name is unique.
 *
 * @param id The unique identifier for the entry, auto-generated by the database.
 * @param packageName The package name of the application added by the user.
 */
@Entity(
    tableName = "PackageNameAddedByUserTable",
    indices = [
        Index("id", unique = true),
        Index("packageName", unique = true)
    ]
)
data class PackageNameAddedByUserEntry(
    @PrimaryKey(autoGenerate = true) val id:Int = 0,
    val packageName:String
)