package com.xxmrk888ytxx.database.Entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * [Entity] for storing information about applications that are being tracked.
 *
 * This entity is used to represent an app whose activity is monitored.
 * Each tracked app is identified by a unique package name.
 *
 * @param id The unique identifier for the entity, automatically generated by the database.
 * @param packageName The unique package name of the tracked application (e.g., "com.example.app").
 */
@Entity(
    tableName = "TrackedAppTable",
    indices = [
        Index("id", unique = true),
        Index("packageName", unique = true)
    ]
)
data class TrackedAppEntity(
    @PrimaryKey(autoGenerate = true) val id:Int = 0,
    val packageName:String
)